services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library_system

  postgres:
    image: postgres:latest
    environment:
      DATABASE_URL: postgres://username:password@postgres:5432/library_system
